//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub date: DateTime,
    pub r#type: String,
    pub fk_firma: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::firma::Entity",
        from = "Column::FkFirma",
        to = "super::firma::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Firma,
}

impl Related<super::firma::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Firma.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
